export const GAME_NAMES = {
  drinking: 'วงเหล้า',
  spyfall: 'สปายฟอล',
  target: 'เลขเป้า',
  werewolf: 'หมาป่า (ดิจิทัล)',
  werewolf_physical: 'หมาป่า (ไพ่จริง)',
  truthordare: 'จริงหรือกล้า',
  quiz: 'ควิซ',
  drawing: 'วาดรูปทายคำ',
  wouldyourather: 'เลือกข้าง',
  wordbomb: 'บอมบ์คำ',
  neverhaveiever: 'ไม่เคย...',
  taboo: 'ใบ้คำ',
  mathrace: 'คำนวณเร็ว',
  twentyquestions: 'Insider',
  fakeartist: 'ศิลปินปลอม',
  blackjack: 'แบล็คแจ็ค',
  slaves: 'สลาฟ',
  poker: 'โป๊กเกอร์',
};

export const GAME_ICONS = {
  drinking: '🍺',
  spyfall: '🕵️‍♂️',
  target: '🎯',
  werewolf: '🐺',
  werewolf_physical: '🎴',
  truthordare: '🎭',
  quiz: '🧠',
  drawing: '🎨',
  wouldyourather: '⚖️',
  wordbomb: '💣',
  neverhaveiever: '🙋',
  taboo: '🤫',
  mathrace: '🔢',
  twentyquestions: '🕵️',
  fakeartist: '🎭',
  blackjack: '🃏',
  slaves: '👑',
  poker: '💵',
};
