// @ts-nocheck
const words = [
  // สัตว์
  { word: 'ช้าง', category: 'สัตว์' },
  { word: 'แมวส้ม', category: 'สัตว์' },
  { word: 'ปลาฉลาม', category: 'สัตว์' },
  { word: 'นกยูง', category: 'สัตว์' },
  { word: 'หมีแพนด้า', category: 'สัตว์' },
  { word: 'ปลาหมึกยักษ์', category: 'สัตว์' },
  { word: 'ค้างคาว', category: 'สัตว์' },
  { word: 'นกฮูก', category: 'สัตว์' },
  { word: 'แมงกะพรุน', category: 'สัตว์' },
  { word: 'กิ้งก่า', category: 'สัตว์' },
  { word: 'โลมา', category: 'สัตว์' },
  { word: 'เสือ', category: 'สัตว์' },
  { word: 'ม้าลาย', category: 'สัตว์' },
  { word: 'นกแก้ว', category: 'สัตว์' },
  { word: 'จระเข้', category: 'สัตว์' },
  { word: 'หมึกสาย', category: 'สัตว์' },
  { word: 'กระต่าย', category: 'สัตว์' },
  { word: 'อูฐ', category: 'สัตว์' },
  { word: 'เพนกวิน', category: 'สัตว์' },
  { word: 'แรด', category: 'สัตว์' },
  { word: 'หมูป่า', category: 'สัตว์' },
  { word: 'นกกระจอกเทศ', category: 'สัตว์' },
  { word: 'ปลาการ์ตูน', category: 'สัตว์' },
  { word: 'แมงมุม', category: 'สัตว์' },
  { word: 'ม้าน้ำ', category: 'สัตว์' },
  { word: 'หมาป่า', category: 'สัตว์' },
  { word: 'นกฟลามิงโก', category: 'สัตว์' },
  { word: 'กวาง', category: 'สัตว์' },
  { word: 'หมีขั้วโลก', category: 'สัตว์' },
  { word: 'งูเห่า', category: 'สัตว์' },
  { word: 'ยีราฟ', category: 'สัตว์' },
  { word: 'แมวน้ำ', category: 'สัตว์' },
  { word: 'ปลาปักเป้า', category: 'สัตว์' },
  { word: 'นกเพนกวิน', category: 'สัตว์' },
  { word: 'ตุ๊กแก', category: 'สัตว์' },
  { word: 'ควายไทย', category: 'สัตว์' },
  { word: 'ปลากัด', category: 'สัตว์' },
  { word: 'นกเงือก', category: 'สัตว์' },
  { word: 'ช้างเผือก', category: 'สัตว์' },
  { word: 'ลิงแสม', category: 'สัตว์' },
  { word: 'เต่าตนุ', category: 'สัตว์' },
  { word: 'สุนัขไทยหลังอาน', category: 'สัตว์' },
  { word: 'แมวโคราช', category: 'สัตว์' },
  { word: 'ปลาช่อน', category: 'สัตว์' },
  { word: 'ตะกวด', category: 'สัตว์' },
  { word: 'กระทิง', category: 'สัตว์' },
  { word: 'นกกาเหว่า', category: 'สัตว์' },
  { word: 'ปูม้า', category: 'สัตว์' },
  { word: 'ชะนี', category: 'สัตว์' },

  // อาหาร
  { word: 'ส้มตำ', category: 'อาหาร' },
  { word: 'ข้าวมันไก่', category: 'อาหาร' },
  { word: 'ต้มยำกุ้ง', category: 'อาหาร' },
  { word: 'ซูชิ', category: 'อาหาร' },
  { word: 'พิซซ่า', category: 'อาหาร' },
  { word: 'ชาไข่มุก', category: 'อาหาร' },
  { word: 'ผัดกะเพรา', category: 'อาหาร' },
  { word: 'หมูกระทะ', category: 'อาหาร' },
  { word: 'ราเมน', category: 'อาหาร' },
  { word: 'ไก่ทอด', category: 'อาหาร' },
  { word: 'มาม่า', category: 'อาหาร' },
  { word: 'ข้าวเหนียวมะม่วง', category: 'อาหาร' },
  { word: 'แกงเขียวหวาน', category: 'อาหาร' },
  { word: 'ผัดไทย', category: 'อาหาร' },
  { word: 'ข้าวซอย', category: 'อาหาร' },
  { word: 'โจ๊ก', category: 'อาหาร' },
  { word: 'ลูกชิ้นปิ้ง', category: 'อาหาร' },
  { word: 'หม่าล่า', category: 'อาหาร' },
  { word: 'ชาบู', category: 'อาหาร' },
  { word: 'ขนมครก', category: 'อาหาร' },
  { word: 'กะเพราหมูกรอบ', category: 'อาหาร' },
  { word: 'ข้าวผัด', category: 'อาหาร' },
  { word: 'แฮมเบอร์เกอร์', category: 'อาหาร' },
  { word: 'ไอศกรีม', category: 'อาหาร' },
  { word: 'ส้มตำปูปลาร้า', category: 'อาหาร' },
  { word: 'ข้าวกะเพราไข่ดาว', category: 'อาหาร' },
  { word: 'ลาบหมู', category: 'อาหาร' },
  { word: 'น้ำตกหมู', category: 'อาหาร' },
  { word: 'ข้าวเหนียวหมูปิ้ง', category: 'อาหาร' },
  { word: 'กุ้งเผา', category: 'อาหาร' },
  { word: 'หอยทอด', category: 'อาหาร' },
  { word: 'ข้าวหมกไก่', category: 'อาหาร' },
  { word: 'ก๋วยเตี๋ยวเรือ', category: 'อาหาร' },
  { word: 'ทาโก้', category: 'อาหาร' },
  { word: 'โดนัท', category: 'อาหาร' },
  { word: 'แกงมัสมั่น', category: 'อาหาร' },
  { word: 'ไส้กรอกอีสาน', category: 'อาหาร' },
  { word: 'ข้าวเกรียบปากหม้อ', category: 'อาหาร' },
  { word: 'กุ้งแม่น้ำเผา', category: 'อาหาร' },
  { word: 'ยำวุ้นเส้น', category: 'อาหาร' },
  { word: 'แกงส้มชะอม', category: 'อาหาร' },
  { word: 'ข้าวยำ', category: 'อาหาร' },
  { word: 'หมูสะเต๊ะ', category: 'อาหาร' },
  { word: 'ขนมจีนน้ำยา', category: 'อาหาร' },
  { word: 'ทอดมันปลากราย', category: 'อาหาร' },
  { word: 'แกงเลียง', category: 'อาหาร' },
  { word: 'ข้าวต้มกุ้ง', category: 'อาหาร' },
  { word: 'ปอเปี๊ยะทอด', category: 'อาหาร' },
  { word: 'ขนมบัวลอย', category: 'อาหาร' },

  // สถานที่
  { word: 'วัดพระแก้ว', category: 'สถานที่' },
  { word: 'สยามพารากอน', category: 'สถานที่' },
  { word: 'เกาะพีพี', category: 'สถานที่' },
  { word: 'หอไอเฟล', category: 'สถานที่' },
  { word: 'เยาวราช', category: 'สถานที่' },
  { word: 'ดอยอินทนนท์', category: 'สถานที่' },
  { word: 'ตลาดนัดจตุจักร', category: 'สถานที่' },
  { word: 'ดิสนีย์แลนด์', category: 'สถานที่' },
  { word: 'ถนนข้าวสาร', category: 'สถานที่' },
  { word: 'สนามหลวง', category: 'สถานที่' },
  { word: 'เขาใหญ่', category: 'สถานที่' },
  { word: 'พัทยา', category: 'สถานที่' },
  { word: 'เชียงใหม่', category: 'สถานที่' },
  { word: 'สะพานมอญ', category: 'สถานที่' },
  { word: 'อยุธยา', category: 'สถานที่' },
  { word: 'ตลาดน้ำ', category: 'สถานที่' },
  { word: 'เซเว่น', category: 'สถานที่' },
  { word: 'ห้องสมุด', category: 'สถานที่' },
  { word: 'สนามบินสุวรรณภูมิ', category: 'สถานที่' },
  { word: 'วัดอรุณ', category: 'สถานที่' },
  { word: 'เขาสก', category: 'สถานที่' },
  { word: 'หัวหิน', category: 'สถานที่' },
  { word: 'สมุย', category: 'สถานที่' },
  { word: 'ภูเก็ต', category: 'สถานที่' },
  { word: 'กรุงโรม', category: 'สถานที่' },
  { word: 'โตเกียว', category: 'สถานที่' },
  { word: 'ลอนดอน', category: 'สถานที่' },
  { word: 'นิวยอร์ก', category: 'สถานที่' },
  { word: 'ตลาดโรงเกลือ', category: 'สถานที่' },
  { word: 'สวนจตุจักร', category: 'สถานที่' },
  { word: 'วัดโพธิ์', category: 'สถานที่' },
  { word: 'ปารีส', category: 'สถานที่' },
  { word: 'สนามกีฬา', category: 'สถานที่' },
  { word: 'โรงพยาบาล', category: 'สถานที่' },
  { word: 'ท่าพระจันทร์', category: 'สถานที่' },
  { word: 'เขาวัง เพชรบุรี', category: 'สถานที่' },
  { word: 'ถนนคนเดิน เชียงใหม่', category: 'สถานที่' },
  { word: 'ตลาดร่มหุบ', category: 'สถานที่' },
  { word: 'เกาะเสม็ด', category: 'สถานที่' },
  { word: 'พระธาตุดอยสุเทพ', category: 'สถานที่' },
  { word: 'ตลาดอมพวา', category: 'สถานที่' },
  { word: 'เมืองโบราณ', category: 'สถานที่' },
  { word: 'ถนนสีลม', category: 'สถานที่' },
  { word: 'สำเพ็ง', category: 'สถานที่' },
  { word: 'วัดร่องขุ่น', category: 'สถานที่' },
  { word: 'เขื่อนเชี่ยวหลาน', category: 'สถานที่' },
  { word: 'อุทยานประวัติศาสตร์สุโขทัย', category: 'สถานที่' },
  { word: 'MBK Center', category: 'สถานที่' },

  // บุคคล
  { word: 'ลิซ่า BLACKPINK', category: 'บุคคล' },
  { word: 'อีลอน มัสก์', category: 'บุคคล' },
  { word: 'เทย์เลอร์ สวิฟต์', category: 'บุคคล' },
  { word: 'โดราเอมอน', category: 'บุคคล' },
  { word: 'สตีฟ จ็อบส์', category: 'บุคคล' },
  { word: 'แฮร์รี่ พอตเตอร์', category: 'บุคคล' },
  { word: 'ชนาธิป', category: 'บุคคล' },
  { word: 'พี่ตูน บอดี้สแลม', category: 'บุคคล' },
  { word: 'มาริโอ้', category: 'บุคคล' },
  { word: 'ซน โกคู', category: 'บุคคล' },
  { word: 'โอปอล์', category: 'บุคคล' },
  { word: 'BamBam GOT7', category: 'บุคคล' },
  { word: 'ครูพี่แนน', category: 'บุคคล' },
  { word: 'ป๋อมแป๋ม', category: 'บุคคล' },
  { word: 'มิลลิ', category: 'บุคคล' },
  { word: 'นารูโตะ', category: 'บุคคล' },
  { word: 'ลุฟี่', category: 'บุคคล' },
  { word: 'ไอรอนแมน', category: 'บุคคล' },
  { word: 'ซานตาคลอส', category: 'บุคคล' },
  { word: 'ป้าทิพย์', category: 'บุคคล' },
  { word: 'พี่หมื่นศรีเรือน', category: 'บุคคล' },
  { word: 'ปิกาจู', category: 'บุคคล' },
  { word: 'สมเด็จพระนเรศวร', category: 'บุคคล' },
  { word: 'ไอน์สไตน์', category: 'บุคคล' },
  { word: 'เมสซี่', category: 'บุคคล' },
  { word: 'โรนัลโด้', category: 'บุคคล' },
  { word: 'เจมส์ บอนด์', category: 'บุคคล' },
  { word: 'สไปเดอร์แมน', category: 'บุคคล' },
  { word: 'โจ๊กเกอร์', category: 'บุคคล' },
  { word: 'ท่านขุนทอง', category: 'บุคคล' },
  { word: 'พี่จอง BTS', category: 'บุคคล' },
  { word: 'เทพกระดาน', category: 'บุคคล' },
  { word: 'คุณชายพุฒิภัทร', category: 'บุคคล' },
  { word: 'ปังปอนด์', category: 'บุคคล' },
  { word: 'พ่อขุนรามคำแหง', category: 'บุคคล' },
  { word: 'ท้าวสุรนารี (ย่าโม)', category: 'บุคคล' },
  { word: 'สุนทรภู่', category: 'บุคคล' },
  { word: 'แอน ทองประสม', category: 'บุคคล' },
  { word: 'น้าค่อม', category: 'บุคคล' },
  { word: 'อ๊อฟ ปองศักดิ์', category: 'บุคคล' },
  { word: 'โน้ส อุดม', category: 'บุคคล' },
  { word: 'ทูน หิรัญทรัพย์', category: 'บุคคล' },
  { word: 'เบิร์ด ธงไชย', category: 'บุคคล' },
  { word: 'แสตมป์ อภิวัชร์', category: 'บุคคล' },
  { word: 'ลุงตู่', category: 'บุคคล' },
  { word: 'พี่เจ เจตริน', category: 'บุคคล' },
  { word: 'ใหม่ ดาวิกา', category: 'บุคคล' },
  { word: 'มาร์กี้ ราศรี', category: 'บุคคล' },

  // สิ่งของ
  { word: 'ร่ม', category: 'สิ่งของ' },
  { word: 'ไอโฟน', category: 'สิ่งของ' },
  { word: 'กระจก', category: 'สิ่งของ' },
  { word: 'หมอนข้าง', category: 'สิ่งของ' },
  { word: 'กล้องถ่ายรูป', category: 'สิ่งของ' },
  { word: 'แว่นกันแดด', category: 'สิ่งของ' },
  { word: 'พัดลม', category: 'สิ่งของ' },
  { word: 'หูฟัง', category: 'สิ่งของ' },
  { word: 'ลูกโป่ง', category: 'สิ่งของ' },
  { word: 'ไฟแช็ก', category: 'สิ่งของ' },
  { word: 'กระเป๋าเป้', category: 'สิ่งของ' },
  { word: 'นาฬิกา', category: 'สิ่งของ' },
  { word: 'รีโมท', category: 'สิ่งของ' },
  { word: 'เตารีด', category: 'สิ่งของ' },
  { word: 'กรรไกร', category: 'สิ่งของ' },
  { word: 'ไม้แขวนเสื้อ', category: 'สิ่งของ' },
  { word: 'ปากกา', category: 'สิ่งของ' },
  { word: 'ตู้เย็น', category: 'สิ่งของ' },
  { word: 'โคมไฟ', category: 'สิ่งของ' },
  { word: 'กุญแจ', category: 'สิ่งของ' },
  { word: 'ไม้กวาด', category: 'สิ่งของ' },
  { word: 'แปรงสีฟัน', category: 'สิ่งของ' },
  { word: 'ถุงมือ', category: 'สิ่งของ' },
  { word: 'จอคอม', category: 'สิ่งของ' },
  { word: 'เครื่องปั่น', category: 'สิ่งของ' },
  { word: 'ผ้าเช็ดตัว', category: 'สิ่งของ' },
  { word: 'ไม้บรรทัด', category: 'สิ่งของ' },
  { word: 'ลิปสติก', category: 'สิ่งของ' },
  { word: 'หมวกกันน็อค', category: 'สิ่งของ' },
  { word: 'สายชาร์จ', category: 'สิ่งของ' },
  { word: 'กระติกน้ำ', category: 'สิ่งของ' },
  { word: 'เข็มขัด', category: 'สิ่งของ' },
  { word: 'ถังขยะ', category: 'สิ่งของ' },
  { word: 'เครื่องซักผ้า', category: 'สิ่งของ' },
  { word: 'ครกตำส้มตำ', category: 'สิ่งของ' },
  { word: 'กระติ๊บข้าว', category: 'สิ่งของ' },
  { word: 'พวงมาลัยดอกไม้', category: 'สิ่งของ' },
  { word: 'เตาถ่าน', category: 'สิ่งของ' },
  { word: 'กระทง', category: 'สิ่งของ' },
  { word: 'พัดใบตาล', category: 'สิ่งของ' },
  { word: 'ตุ๊กตาท่านผู้หญิง', category: 'สิ่งของ' },
  { word: 'ถุงก๊อปแก๊ป', category: 'สิ่งของ' },
  { word: 'บัตรแรบบิท', category: 'สิ่งของ' },
  { word: 'เสื้อวิน', category: 'สิ่งของ' },
  { word: 'พระเครื่อง', category: 'สิ่งของ' },
  { word: 'ธูปเทียน', category: 'สิ่งของ' },
  { word: 'ชุดนักเรียนไทย', category: 'สิ่งของ' },
  { word: 'รถตุ๊กตุ๊ก', category: 'สิ่งของ' },

  // กีฬา
  { word: 'มวยไทย', category: 'กีฬา' },
  { word: 'เซิร์ฟบอร์ด', category: 'กีฬา' },
  { word: 'โยคะ', category: 'กีฬา' },
  { word: 'แบดมินตัน', category: 'กีฬา' },
  { word: 'ดำน้ำ', category: 'กีฬา' },
  { word: 'โบว์ลิ่ง', category: 'กีฬา' },
  { word: 'วิ่งมาราธอน', category: 'กีฬา' },
  { word: 'ฟุตบอล', category: 'กีฬา' },
  { word: 'บาสเกตบอล', category: 'กีฬา' },
  { word: 'ปิงปอง', category: 'กีฬา' },
  { word: 'กอล์ฟ', category: 'กีฬา' },
  { word: 'มวยปล้ำ', category: 'กีฬา' },
  { word: 'สเก็ตบอร์ด', category: 'กีฬา' },
  { word: 'ว่ายน้ำ', category: 'กีฬา' },
  { word: 'เทนนิส', category: 'กีฬา' },
  { word: 'ยิงธนู', category: 'กีฬา' },
  { word: 'ปีนผา', category: 'กีฬา' },
  { word: 'วอลเลย์บอล', category: 'กีฬา' },
  { word: 'ยูโด', category: 'กีฬา' },
  { word: 'เบสบอล', category: 'กีฬา' },
  { word: 'คาราเต้', category: 'กีฬา' },
  { word: 'กระโดดร่ม', category: 'กีฬา' },
  { word: 'พายเรือ', category: 'กีฬา' },
  { word: 'ยกน้ำหนัก', category: 'กีฬา' },
  { word: 'เทควันโด', category: 'กีฬา' },
  { word: 'ฟันดาบ', category: 'กีฬา' },
  { word: 'ฮอกกี้', category: 'กีฬา' },
  { word: 'รักบี้', category: 'กีฬา' },
  { word: 'แข่งรถ F1', category: 'กีฬา' },
  { word: 'วิ่งผลัด', category: 'กีฬา' },
  { word: 'กระโดดสูง', category: 'กีฬา' },
  { word: 'ยิมนาสติก', category: 'กีฬา' },
  { word: 'มวยสากล', category: 'กีฬา' },
  { word: 'ขี่ม้า', category: 'กีฬา' },
  { word: 'ตะกร้อ', category: 'กีฬา' },
  { word: 'ชกมวยลุมพินี', category: 'กีฬา' },
  { word: 'แข่งเรือยาว', category: 'กีฬา' },
  { word: 'ว่าวจุฬา', category: 'กีฬา' },
  { word: 'กระบี่กระบอง', category: 'กีฬา' },
  { word: 'วิ่งควาย ชลบุรี', category: 'กีฬา' },
  { word: 'แข่งเรือพาย', category: 'กีฬา' },
  { word: 'เปตอง', category: 'กีฬา' },
  { word: 'ชี้นิ้ว', category: 'กีฬา' },
  { word: 'แข่งว่ายน้ำข้ามแม่น้ำโขง', category: 'กีฬา' },
  { word: 'แข่งจักรยานทางไกล', category: 'กีฬา' },
  { word: 'ฟุตซอล', category: 'กีฬา' },
  { word: 'กีฬาสี', category: 'กีฬา' },
  { word: 'วิ่งมินิมาราธอน', category: 'กีฬา' },

  // ภาพยนตร์
  { word: 'Squid Game', category: 'ภาพยนตร์' },
  { word: 'Avengers', category: 'ภาพยนตร์' },
  { word: 'Harry Potter', category: 'ภาพยนตร์' },
  { word: 'One Piece', category: 'ภาพยนตร์' },
  { word: 'Frozen', category: 'ภาพยนตร์' },
  { word: 'Spider-Man', category: 'ภาพยนตร์' },
  { word: 'พี่มาก..พระโขนง', category: 'ภาพยนตร์' },
  { word: 'ฉลาดเกมส์โกง', category: 'ภาพยนตร์' },
  { word: 'Fast & Furious', category: 'ภาพยนตร์' },
  { word: 'Titanic', category: 'ภาพยนตร์' },
  { word: 'Jurassic Park', category: 'ภาพยนตร์' },
  { word: 'Star Wars', category: 'ภาพยนตร์' },
  { word: 'Batman', category: 'ภาพยนตร์' },
  { word: 'นาคี', category: 'ภาพยนตร์' },
  { word: 'Demon Slayer', category: 'ภาพยนตร์' },
  { word: 'Toy Story', category: 'ภาพยนตร์' },
  { word: 'The Lion King', category: 'ภาพยนตร์' },
  { word: 'Attack on Titan', category: 'ภาพยนตร์' },
  { word: 'Minecraft: The Movie', category: 'ภาพยนตร์' },
  { word: 'John Wick', category: 'ภาพยนตร์' },
  { word: 'Interstellar', category: 'ภาพยนตร์' },
  { word: 'The Matrix', category: 'ภาพยนตร์' },
  { word: 'Parasite', category: 'ภาพยนตร์' },
  { word: 'Shrek', category: 'ภาพยนตร์' },
  { word: 'Finding Nemo', category: 'ภาพยนตร์' },
  { word: 'Inception', category: 'ภาพยนตร์' },
  { word: 'Your Name', category: 'ภาพยนตร์' },
  { word: 'เพื่อนสนิท', category: 'ภาพยนตร์' },
  { word: 'ปิดเทอมใหญ่หัวใจว้าวุ่น', category: 'ภาพยนตร์' },
  { word: 'Transformers', category: 'ภาพยนตร์' },
  { word: 'Inside Out', category: 'ภาพยนตร์' },
  { word: 'Barbie', category: 'ภาพยนตร์' },
  { word: 'Mission Impossible', category: 'ภาพยนตร์' },
  { word: 'Jaws', category: 'ภาพยนตร์' },
  { word: 'บุพเพสันนิวาส', category: 'ภาพยนตร์' },
  { word: 'องค์บาก', category: 'ภาพยนตร์' },
  { word: 'แฟนฉัน', category: 'ภาพยนตร์' },
  { word: 'ชัตเตอร์ กดติดวิญญาณ', category: 'ภาพยนตร์' },
  { word: 'รักแห่งสยาม', category: 'ภาพยนตร์' },
  { word: 'ต้มยำกุ้ง (หนัง)', category: 'ภาพยนตร์' },
  { word: 'โหมด', category: 'ภาพยนตร์' },
  { word: 'เด็กหอ', category: 'ภาพยนตร์' },
  { word: 'ลัดดาแลนด์', category: 'ภาพยนตร์' },
  { word: 'ไทบ้าน', category: 'ภาพยนตร์' },
  { word: 'สัปเหร่อ', category: 'ภาพยนตร์' },
  { word: 'ธี่หยด', category: 'ภาพยนตร์' },
  { word: 'ร่างทรง', category: 'ภาพยนตร์' },
  { word: 'สี่แพร่ง', category: 'ภาพยนตร์' },

  // ปั่นๆ ฮาๆ
  { word: 'คนนอนดึก', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนกินจุ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ตื่นสาย', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนเมารถ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'WiFi สาธารณะ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ลืมรหัสผ่าน', category: 'ปั่นๆ ฮาๆ' },
  { word: 'เบาะรถเมล์', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนถ่ายรูปอาหาร', category: 'ปั่นๆ ฮาๆ' },
  { word: 'แอร์ห้องประชุม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ลิฟต์เต็ม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนแชทช้า', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนส่งสติกเกอร์ท่วม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'เพื่อนยืมเงิน', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คิวหมอ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนลืมชื่อ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'รถติด', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ฝนตกไม่พกร่ม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนอ่าน seen ไม่ตอบ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนแย่งปลั๊กชาร์จ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนตัดคิว', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนเปิดลำโพงในรถไฟฟ้า', category: 'ปั่นๆ ฮาๆ' },
  { word: 'โปรเน็ตหมด', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ห้องน้ำสาธารณะ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนพูดสปอยล์หนัง', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ส่งข้อความผิดกลุ่ม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'โทรศัพท์ตกส้วม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนกดลิฟต์ทุกชั้น', category: 'ปั่นๆ ฮาๆ' },
  { word: 'เดทแรก', category: 'ปั่นๆ ฮาๆ' },
  { word: 'แอปหาคู่', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ประชุมที่ควรเป็นอีเมล', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนตื่นสายวันจันทร์', category: 'ปั่นๆ ฮาๆ' },
  { word: 'เมนูหมด', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนจามไม่ปิดปาก', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ถุงเท้าไม่เข้าคู่', category: 'ปั่นๆ ฮาๆ' },
  { word: 'แฟนเก่า', category: 'ปั่นๆ ฮาๆ' },
  { word: 'Friend Zone', category: 'ปั่นๆ ฮาๆ' },
  { word: 'Ghosting', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนโพสต์ฟิตเนส', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ดราม่าออนไลน์', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนนินทา', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนขี้เกียจ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนลืมกุญแจ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนเสียบหูฟังไม่สนิท', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนพูดคนเดียว', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนหลับในห้องประชุม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนส่งเสียงเมนูเรียกเสียงดัง', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนลืมปิดไมค์ Zoom', category: 'ปั่นๆ ฮาๆ' },
  { word: 'แบตหมดตอนสำคัญ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนถ่ายเซลฟี่ทุกที่', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนโทรมาไม่รับ แล้วแชทถามว่าไง', category: 'ปั่นๆ ฮาๆ' },
  { word: 'นาฬิกาปลุกแล้วกดเลื่อน', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนกินเสียงดังในโรงหนัง', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนจอดรถทับเส้น', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนนัดเจอแล้วมาสาย', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนดู TikTok เสียงดัง', category: 'ปั่นๆ ฮาๆ' },
  { word: 'มอเตอร์ไซค์รับจ้างขับเร็ว', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนขายลอตเตอรี่ตื้อ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'สงกรานต์ โดนสาดน้ำไม่ทันตั้งตัว', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนเข้าแถวซื้อของดังแล้วหมด', category: 'ปั่นๆ ฮาๆ' },
  { word: 'แก๊งคอลเซ็นเตอร์', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนจอดรถซ้อนคัน', category: 'ปั่นๆ ฮาๆ' },
  { word: 'รถเมล์ผ่านไม่จอด', category: 'ปั่นๆ ฮาๆ' },
  { word: 'บัตรคนจนหมดเงิน', category: 'ปั่นๆ ฮาๆ' },
  { word: 'โปรโมชั่นเงื่อนไขเยอะ', category: 'ปั่นๆ ฮาๆ' },
  { word: 'แอปเป๋าตัง', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนส่ง LINE สวัสดีวันจันทร์', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนแชร์ข่าวปลอม', category: 'ปั่นๆ ฮาๆ' },
  { word: 'ออกจากเซเว่นมือเปล่าไม่ได้', category: 'ปั่นๆ ฮาๆ' },
  { word: 'คนไลฟ์ขายของตอนตี 3', category: 'ปั่นๆ ฮาๆ' },
];

export const ALL_CATEGORIES = [...new Set(words.map(w => w.category))];

export function getRandomWord(usedWords = [], filterCategories = '') {
  let pool = words;
  if (filterCategories) {
    const cats = Array.isArray(filterCategories) ? filterCategories : [filterCategories];
    if (cats.length > 0) {
      pool = words.filter(w => cats.includes(w.category));
      if (pool.length === 0) pool = words;
    }
  }
  const available = pool.filter(w => !usedWords.includes(w.word));
  if (available.length === 0) return pool[Math.floor(Math.random() * pool.length)];
  return available[Math.floor(Math.random() * available.length)];
}

export function getWordChoices(count = 3, usedWords = []) {
  const available = words.filter(w => !usedWords.includes(w.word));
  if (available.length === 0) return [words[0]];
  const shuffled = [...available].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export default words;
